CFLAGS += -DTARGET_BUILD_VARIANT=$(shell echo $(TARGET_BUILD_VARIANT))

ifeq ($(TARGET_BUILD_VARIANT), eng)
CFLAGS += -DTARGET_BUILD_VARIANT_$(TARGET_BUILD_VARIANT)
else ifeq ($(TARGET_BUILD_VARIANT), userdebug)
CFLAGS += -DTARGET_BUILD_VARIANT_$(TARGET_BUILD_VARIANT)
else
CFLAGS += -DTARGET_BUILD_VARIANT_$(TARGET_BUILD_VARIANT)
endif

$(info CFLAGS: $(CFLAGS))

all:
	gcc main.c -o define $(CFLAGS)

clean:
	rm define
